// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package current.session.riferrei;

/**
 * Protobuf type {@code Person}
 */
public final class Person extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Person)
    PersonOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Person.newBuilder() to construct.
  private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Person() {
    userName_ = "";
    interests_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Person();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return current.session.riferrei.PersonOuterClass.internal_static_Person_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return current.session.riferrei.PersonOuterClass.internal_static_Person_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            current.session.riferrei.Person.class, current.session.riferrei.Person.Builder.class);
  }

  private int bitField0_;
  public static final int USERNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object userName_;
  /**
   * <code>string userName = 1;</code>
   * @return The userName.
   */
  @java.lang.Override
  public java.lang.String getUserName() {
    java.lang.Object ref = userName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userName_ = s;
      return s;
    }
  }
  /**
   * <code>string userName = 1;</code>
   * @return The bytes for userName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserNameBytes() {
    java.lang.Object ref = userName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FAVORITENUMBER_FIELD_NUMBER = 2;
  private long favoriteNumber_;
  /**
   * <code>optional int64 favoriteNumber = 2;</code>
   * @return Whether the favoriteNumber field is set.
   */
  @java.lang.Override
  public boolean hasFavoriteNumber() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int64 favoriteNumber = 2;</code>
   * @return The favoriteNumber.
   */
  @java.lang.Override
  public long getFavoriteNumber() {
    return favoriteNumber_;
  }

  public static final int INTERESTS_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList interests_;
  /**
   * <code>repeated string interests = 3;</code>
   * @return A list containing the interests.
   */
  public com.google.protobuf.ProtocolStringList
      getInterestsList() {
    return interests_;
  }
  /**
   * <code>repeated string interests = 3;</code>
   * @return The count of interests.
   */
  public int getInterestsCount() {
    return interests_.size();
  }
  /**
   * <code>repeated string interests = 3;</code>
   * @param index The index of the element to return.
   * @return The interests at the given index.
   */
  public java.lang.String getInterests(int index) {
    return interests_.get(index);
  }
  /**
   * <code>repeated string interests = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the interests at the given index.
   */
  public com.google.protobuf.ByteString
      getInterestsBytes(int index) {
    return interests_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userName_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt64(2, favoriteNumber_);
    }
    for (int i = 0; i < interests_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, interests_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userName_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, favoriteNumber_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < interests_.size(); i++) {
        dataSize += computeStringSizeNoTag(interests_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getInterestsList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof current.session.riferrei.Person)) {
      return super.equals(obj);
    }
    current.session.riferrei.Person other = (current.session.riferrei.Person) obj;

    if (!getUserName()
        .equals(other.getUserName())) return false;
    if (hasFavoriteNumber() != other.hasFavoriteNumber()) return false;
    if (hasFavoriteNumber()) {
      if (getFavoriteNumber()
          != other.getFavoriteNumber()) return false;
    }
    if (!getInterestsList()
        .equals(other.getInterestsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUserName().hashCode();
    if (hasFavoriteNumber()) {
      hash = (37 * hash) + FAVORITENUMBER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFavoriteNumber());
    }
    if (getInterestsCount() > 0) {
      hash = (37 * hash) + INTERESTS_FIELD_NUMBER;
      hash = (53 * hash) + getInterestsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static current.session.riferrei.Person parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static current.session.riferrei.Person parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static current.session.riferrei.Person parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static current.session.riferrei.Person parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static current.session.riferrei.Person parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static current.session.riferrei.Person parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static current.session.riferrei.Person parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static current.session.riferrei.Person parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static current.session.riferrei.Person parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static current.session.riferrei.Person parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static current.session.riferrei.Person parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static current.session.riferrei.Person parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(current.session.riferrei.Person prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Person}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Person)
      current.session.riferrei.PersonOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return current.session.riferrei.PersonOuterClass.internal_static_Person_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return current.session.riferrei.PersonOuterClass.internal_static_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              current.session.riferrei.Person.class, current.session.riferrei.Person.Builder.class);
    }

    // Construct using current.session.riferrei.Person.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      userName_ = "";

      favoriteNumber_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      interests_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return current.session.riferrei.PersonOuterClass.internal_static_Person_descriptor;
    }

    @java.lang.Override
    public current.session.riferrei.Person getDefaultInstanceForType() {
      return current.session.riferrei.Person.getDefaultInstance();
    }

    @java.lang.Override
    public current.session.riferrei.Person build() {
      current.session.riferrei.Person result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public current.session.riferrei.Person buildPartial() {
      current.session.riferrei.Person result = new current.session.riferrei.Person(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.userName_ = userName_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.favoriteNumber_ = favoriteNumber_;
        to_bitField0_ |= 0x00000001;
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        interests_ = interests_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.interests_ = interests_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof current.session.riferrei.Person) {
        return mergeFrom((current.session.riferrei.Person)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(current.session.riferrei.Person other) {
      if (other == current.session.riferrei.Person.getDefaultInstance()) return this;
      if (!other.getUserName().isEmpty()) {
        userName_ = other.userName_;
        onChanged();
      }
      if (other.hasFavoriteNumber()) {
        setFavoriteNumber(other.getFavoriteNumber());
      }
      if (!other.interests_.isEmpty()) {
        if (interests_.isEmpty()) {
          interests_ = other.interests_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureInterestsIsMutable();
          interests_.addAll(other.interests_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              userName_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 16: {
              favoriteNumber_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 16
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureInterestsIsMutable();
              interests_.add(s);
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object userName_ = "";
    /**
     * <code>string userName = 1;</code>
     * @return The userName.
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string userName = 1;</code>
     * @return The bytes for userName.
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userName = 1;</code>
     * @param value The userName to set.
     * @return This builder for chaining.
     */
    public Builder setUserName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserName() {
      
      userName_ = getDefaultInstance().getUserName();
      onChanged();
      return this;
    }
    /**
     * <code>string userName = 1;</code>
     * @param value The bytes for userName to set.
     * @return This builder for chaining.
     */
    public Builder setUserNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userName_ = value;
      onChanged();
      return this;
    }

    private long favoriteNumber_ ;
    /**
     * <code>optional int64 favoriteNumber = 2;</code>
     * @return Whether the favoriteNumber field is set.
     */
    @java.lang.Override
    public boolean hasFavoriteNumber() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int64 favoriteNumber = 2;</code>
     * @return The favoriteNumber.
     */
    @java.lang.Override
    public long getFavoriteNumber() {
      return favoriteNumber_;
    }
    /**
     * <code>optional int64 favoriteNumber = 2;</code>
     * @param value The favoriteNumber to set.
     * @return This builder for chaining.
     */
    public Builder setFavoriteNumber(long value) {
      bitField0_ |= 0x00000001;
      favoriteNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 favoriteNumber = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFavoriteNumber() {
      bitField0_ = (bitField0_ & ~0x00000001);
      favoriteNumber_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList interests_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureInterestsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        interests_ = new com.google.protobuf.LazyStringArrayList(interests_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string interests = 3;</code>
     * @return A list containing the interests.
     */
    public com.google.protobuf.ProtocolStringList
        getInterestsList() {
      return interests_.getUnmodifiableView();
    }
    /**
     * <code>repeated string interests = 3;</code>
     * @return The count of interests.
     */
    public int getInterestsCount() {
      return interests_.size();
    }
    /**
     * <code>repeated string interests = 3;</code>
     * @param index The index of the element to return.
     * @return The interests at the given index.
     */
    public java.lang.String getInterests(int index) {
      return interests_.get(index);
    }
    /**
     * <code>repeated string interests = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the interests at the given index.
     */
    public com.google.protobuf.ByteString
        getInterestsBytes(int index) {
      return interests_.getByteString(index);
    }
    /**
     * <code>repeated string interests = 3;</code>
     * @param index The index to set the value at.
     * @param value The interests to set.
     * @return This builder for chaining.
     */
    public Builder setInterests(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureInterestsIsMutable();
      interests_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string interests = 3;</code>
     * @param value The interests to add.
     * @return This builder for chaining.
     */
    public Builder addInterests(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureInterestsIsMutable();
      interests_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string interests = 3;</code>
     * @param values The interests to add.
     * @return This builder for chaining.
     */
    public Builder addAllInterests(
        java.lang.Iterable<java.lang.String> values) {
      ensureInterestsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, interests_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string interests = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearInterests() {
      interests_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string interests = 3;</code>
     * @param value The bytes of the interests to add.
     * @return This builder for chaining.
     */
    public Builder addInterestsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureInterestsIsMutable();
      interests_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Person)
  }

  // @@protoc_insertion_point(class_scope:Person)
  private static final current.session.riferrei.Person DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new current.session.riferrei.Person();
  }

  public static current.session.riferrei.Person getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Person>
      PARSER = new com.google.protobuf.AbstractParser<Person>() {
    @java.lang.Override
    public Person parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Person> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Person> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public current.session.riferrei.Person getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

