// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package current.session.riferrei;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userName = 1;</code>
   * @return The userName.
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 1;</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>optional int64 favoriteNumber = 2;</code>
   * @return Whether the favoriteNumber field is set.
   */
  boolean hasFavoriteNumber();
  /**
   * <code>optional int64 favoriteNumber = 2;</code>
   * @return The favoriteNumber.
   */
  long getFavoriteNumber();

  /**
   * <code>repeated string interests = 3;</code>
   * @return A list containing the interests.
   */
  java.util.List<java.lang.String>
      getInterestsList();
  /**
   * <code>repeated string interests = 3;</code>
   * @return The count of interests.
   */
  int getInterestsCount();
  /**
   * <code>repeated string interests = 3;</code>
   * @param index The index of the element to return.
   * @return The interests at the given index.
   */
  java.lang.String getInterests(int index);
  /**
   * <code>repeated string interests = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the interests at the given index.
   */
  com.google.protobuf.ByteString
      getInterestsBytes(int index);
}
